spring:
  application:
    name: appDemo

  datasource:
    url: jdbc:mysql://petclinic-mysql:3306/registrationdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: ${DB_PASSWORD:apppass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # auto-creates / migrates 'registration' table
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    com.springWeb.appDemo: DEBUG
    org.springframework.web: INFO
